<a href="https://colab.research.google.com/github/Xander50/C-140/blob/main/C_140.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
!pip install kaggle

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.5.13)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from kaggle) (2022.12.7)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.27.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.65.0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.1)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.26.15)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.4)

In [2]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"ripsomeguy69","key":"58788869db3eed520c06dd3b43f53487"}'}

In [87]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle
!chmod 600 ~/.kaggle/kaggle.json

In [88]:
!kaggle datasets download -d tmdb/tmdb-movie-metadata

tmdb-movie-metadata.zip: Skipping, found more recently modified local copy (use --force to force download)

In [89]:
!ls

kaggle.json  tmdb_5000_credits.csv  tmdb-movie-metadata.zip
sample_data  tmdb_5000_movies.csv

In [ ]:
!unzip tmdb-movie-metadata.zip

Archive:  tmdb-movie-metadata.zip
replace tmdb_5000_credits.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [42]:
import pandas as pd
credits_df=pd.read_csv('tmdb_5000_credits.csv')
movies_df=pd.read_csv('tmdb_5000_movies.csv')
credits_df.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [43]:
movies_df.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [44]:
credits_df.rename(columns={'movie_id':'id'},inplace=True)
credits_df.head(3)

,id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [45]:
result_df=pd.merge(movies_df,credits_df,on='id')
result_df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [46]:
#C-139
result_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4803 entries, 0 to 4802
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title_x               4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
 20  title_y               4803 non-null   object
 21  cast                  4803 non-null   object
 22  crew                  4803 non-null   object
dtypes: float64(3), int64(4), object(16)
memory usage: 900.6+ KB

In [47]:
result_df.drop(['homepage','title_x','title_y','production_companies'],axis=1,inplace=True)
result_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4803 entries, 0 to 4802
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   id                    4803 non-null   int64
 3   keywords              4803 non-null   object
 4   original_language     4803 non-null   object
 5   original_title        4803 non-null   object
 6   overview              4800 non-null   object
 7   popularity            4803 non-null   float64
 8   production_countries  4803 non-null   object
 9   release_date          4802 non-null   object
 10  revenue               4803 non-null   int64
 11  runtime               4801 non-null   float64
 12  spoken_languages      4803 non-null   object
 13  status                4803 non-null   object
 14  tagline               3959 non-null   object
 15  vote_average          4803 non-null   float64
 16  vote_count            4803 non-null   int64
 17  cast                  4803 non-null   object
 18  crew                  4803 non-null   object
dtypes: float64(3), int64(4), object(12)
memory usage: 750.5+ KB

In [48]:
result_df.dropna(inplace=True)
result_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3959 entries, 0 to 4801
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                3959 non-null   int64
 1   genres                3959 non-null   object
 2   id                    3959 non-null   int64
 3   keywords              3959 non-null   object
 4   original_language     3959 non-null   object
 5   original_title        3959 non-null   object
 6   overview              3959 non-null   object
 7   popularity            3959 non-null   float64
 8   production_countries  3959 non-null   object
 9   release_date          3959 non-null   object
 10  revenue               3959 non-null   int64
 11  runtime               3959 non-null   float64
 12  spoken_languages      3959 non-null   object
 13  status                3959 non-null   object
 14  tagline               3959 non-null   object
 15  vote_average          3959 non-null   float64
 16  vote_count            3959 non-null   int64
 17  cast                  3959 non-null   object
 18  crew                  3959 non-null   object
dtypes: float64(3), int64(4), object(12)
memory usage: 618.6+ KB

In [15]:
R=result_df['vote_average']
v=result_df['vote_count']
C=result_df['vote_average'].mean()
print(C)

6.181939883809043

In [49]:
m=result_df['vote_count'].quantile(0.9)
print(m)

2104.2000000000003

In [50]:
result_df['weighted_rating']=(R*v+C*m)/(v+m)
result_df[['original_title','weighted_rating']].head()

                             original_title  weighted_rating
0                                    Avatar         7.045931
1  Pirates of the Caribbean: At World's End         6.671215
2                                   Spectre         6.262190
3                     The Dark Knight Rises         7.333824
4                               John Carter         6.140778

In [51]:
result_df.sort_values('weighted_rating',ascending=False,inplace=True)
result_df[['original_title','weighted_rating','vote_average','vote_count','popularity']].head(10)

,original_title,weighted_rating,vote_average,vote_count,popularity
1881,The Shawshank Redemption,8.026863,8.5,8205,136.747729
662,Fight Club,7.913029,8.3,9413,146.757391
65,The Dark Knight,7.898969,8.2,12002,187.322927
3232,Pulp Fiction,7.876838,8.3,8428,121.463076
96,Inception,7.845463,8.1,13752,167.583710
3337,The Godfather,7.816390,8.4,5893,143.659698
95,Interstellar,7.788851,8.1,10867,724.247784
809,Forrest Gump,7.776681,8.2,7927,138.133331
329,The Lord of the Rings: The Return of the King,7.703078,8.1,8064,123.630332
1990,The Empire Strikes Back,7.668083,8.2,5879,78.517830

In [52]:
import plotly.express as px
bar_plot=px.bar(result_df.head(20).sort_values('weighted_rating'),x='weighted_rating',y='original_title',orientation="h")
bar_plot.show()

In [83]:
#c-140
result_df[['original_title','cast','crew','keywords','genres']].head(3)

,original_title,cast,crew,keywords,genres
1881,The Shawshank Redemption,"[Tim Robbins, Morgan Freeman, Bob Gunton, Clan...","[{'credit_id': '52fe4231c3a36847f800b153', 'de...","[{'id': 378, 'name': 'prison'}, {'id': 417, 'n...","[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name..."
662,Fight Club,"[Edward Norton, Brad Pitt, Meat Loaf, Jared Le...","[{'credit_id': '55731b8192514111610027d7', 'de...","[{'id': 825, 'name': 'support group'}, {'id': ...","[{'id': 18, 'name': 'Drama'}]"
65,The Dark Knight,"[Christian Bale, Heath Ledger, Aaron Eckhart, ...","[{'credit_id': '55a0eb4a925141296b0010f8', 'de...","[{'id': 849, 'name': 'dc comics'}, {'id': 853,...","[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name..."

In [84]:
type(result_df.loc[0].at['cast'])

list

In [85]:
from ast import literal_eval
features=['cast','crew','keywords','genres']
for feature in features:

  result_df[feature]=result_df[feature].apply(literal_eval)

ValueError: ignored

In [73]:
type(result_df.loc[0].at['cast'])

list

In [74]:
result_df.loc[6].at['crew']

[{'credit_id': '52fe46db9251416c91062101',
  'department': 'Production',
  'gender': 2,
  'id': 7879,
  'job': 'Executive Producer',
  'name': 'John Lasseter'},
 {'credit_id': '52fe46db9251416c910620e3',
  'department': 'Writing',
  'gender': 2,
  'id': 38748,
  'job': 'Novel',
  'name': 'Jacob Grimm'},
 {'credit_id': '52fe46db9251416c910620dd',
  'department': 'Writing',
  'gender': 2,
  'id': 5448,
  'job': 'Novel',
  'name': 'Wilhelm Grimm'},
 {'credit_id': '572bc6f992514138820000d3',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 8020,
  'job': 'Animation Supervisor',
  'name': 'John Kahrs'},
 {'credit_id': '572bc5d3c3a3687ffd0000a3',
  'department': 'Art',
  'gender': 0,
  'id': 12072,
  'job': 'Production Design',
  'name': 'Douglas Rogers'},
 {'credit_id': '52fe46db9251416c910620e9',
  'department': 'Sound',
  'gender': 2,
  'id': 15813,
  'job': 'Original Music Composer',
  'name': 'Alan Menken'},
 {'credit_id': '572bc54cc3a36801330000b9',
  'department': 'Sound',
  'gender': 2,
  'id': 15813,
  'job': 'Songs',
  'name': 'Alan Menken'},
 {'credit_id': '572bc4c3c3a3687ff90000c2',
  'department': 'Writing',
  'gender': 2,
  'id': 15892,
  'job': 'Screenplay',
  'name': 'Dan Fogelman'},
 {'credit_id': '52fe46db9251416c910620fb',
  'department': 'Production',
  'gender': 0,
  'id': 56612,
  'job': 'Producer',
  'name': 'Roy Conli'},
 {'credit_id': '572bc61492514138900000e1',
  'department': 'Writing',
  'gender': 0,
  'id': 61414,
  'job': 'Story',
  'name': 'Mark Kennedy'},
 {'credit_id': '572bc5c292514138850000c2',
  'department': 'Art',
  'gender': 0,
  'id': 61422,
  'job': 'Co-Art Director',
  'name': 'Dan Cooper'},
 {'credit_id': '572bc56ec3a368013d0000be',
  'department': 'Editing',
  'gender': 2,
  'id': 61958,
  'job': 'Editor',
  'name': 'Tim Mertens'},
 {'credit_id': '572bd492c3a368012f000352',
  'department': 'Sound',
  'gender': 2,
  'id': 65644,
  'job': 'Original Music Composer',
  'name': 'Kevin Kliesch'},
 {'credit_id': '52fe46db9251416c910620bf',
  'department': 'Directing',
  'gender': 2,
  'id': 76595,
  'job': 'Director',
  'name': 'Byron Howard'},
 {'credit_id': '572bd502c3a3687ff90002fd',
  'department': 'Sound',
  'gender': 2,
  'id': 83091,
  'job': 'Sound Re-Recording Mixer',
  'name': 'Dean A. Zupancic'},
 {'credit_id': '572bd4ee92514138940002b8',
  'department': 'Sound',
  'gender': 0,
  'id': 112609,
  'job': 'Sound Re-Recording Mixer',
  'name': 'David E. Fluhr'},
 {'credit_id': '52fe46db9251416c910620ad',
  'department': 'Directing',
  'gender': 2,
  'id': 121830,
  'job': 'Director',
  'name': 'Nathan Greno'},
 {'credit_id': '52fe46db9251416c91062119',
  'department': 'Production',
  'gender': 0,
  'id': 137198,
  'job': 'Casting',
  'name': 'Jamie Sparer Roberts'},
 {'credit_id': '52fe46db9251416c91062107',
  'department': 'Production',
  'gender': 0,
  'id': 139474,
  'job': 'Executive Producer',
  'name': 'Glen Keane'},
 {'credit_id': '572bc6ee92514138850000ec',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 139474,
  'job': 'Animation Supervisor',
  'name': 'Glen Keane'},
 {'credit_id': '572bcbb3c3a3680133000154',
  'department': 'Writing',
  'gender': 0,
  'id': 139474,
  'job': 'Characters',
  'name': 'Glen Keane'},
 {'credit_id': '572bd4cb92514138880002d5',
  'department': 'Crew',
  'gender': 0,
  'id': 928608,
  'job': 'Post Production Supervisor',
  'name': 'Brent W. Hall'},
 {'credit_id': '572bc96c92514138880000f8',
  'department': 'Crew',
  'gender': 0,
  'id': 953331,
  'job': 'Executive Music Producer',
  'name': 'Chris Montan'},
 {'credit_id': '572bc544c3a368012f0000d1',
  'department': 'Sound',
  'gender': 0,
  'id': 1017262,
  'job': 'Songs',
  'name': 'Glenn Slater'},
 {'credit_id': '572bca45c3a3680133000136',
  'department': 'Crew',
  'gender': 0,
  'id': 1123657,
  'job': 'Supervising Animator',
  'name': 'Lino DiSalvo'},
 {'credit_id': '572bc589c3a368012f0000dd',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1210381,
  'job': 'Visual Effects Supervisor',
  'name': 'Steve Goldberg'},
 {'credit_id': '572bc70a92514138850000f0',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1281387,
  'job': 'Animation Supervisor',
  'name': 'Clay Kaytis'},
 {'credit_id': '572bc97ec3a3687ff7000114',
  'department': 'Sound',
  'gender': 0,
  'id': 1291315,
  'job': 'Music Supervisor',
  'name': 'Tom MacDougall'},
 {'credit_id': '572bd51792514138960002cb',
  'department': 'Sound',
  'gender': 1,
  'id': 1367494,
  'job': 'Sound Editor',
  'name': 'Ai-Ling Lee'},
 {'credit_id': '572bcd14c3a3687ff7000184',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1368856,
  'job': 'Visual Development',
  'name': 'Laurent Ben-Mimoun'},
 {'credit_id': '572bca0e925141388e00013a',
  'department': 'Production',
  'gender': 0,
  'id': 1381896,
  'job': 'Production Supervisor',
  'name': 'Tim Pauer'},
 {'credit_id': '572bd539925141388a0002e3',
  'department': 'Sound',
  'gender': 0,
  'id': 1408301,
  'job': 'Sound Editor',
  'name': 'Jason W. Jennings'},
 {'credit_id': '572bc9fb925141388500012e',
  'department': 'Sound',
  'gender': 2,
  'id': 1424167,
  'job': 'Sound Designer',
  'name': 'Cameron Frankley'},
 {'credit_id': '550d7f219251414695005afd',
  'department': 'Production',
  'gender': 0,
  'id': 1443211,
  'job': 'Associate Producer',
  'name': 'Aimee Scribner'},
 {'credit_id': '5543e0cf925141586d0026f3',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1447400,
  'job': 'Visual Development',
  'name': 'James Finn'},
 {'credit_id': '5542343f9251413d6d003a7b',
  'department': 'Directing',
  'gender': 0,
  'id': 1447483,
  'job': 'Layout',
  'name': 'Rick Moore'},
 {'credit_id': '5548cc21c3a368787e0020f1',
  'department': 'Directing',
  'gender': 0,
  'id': 1447497,
  'job': 'Layout',
  'name': 'Merrick Rustia'},
 {'credit_id': '572bcbbec3a368012f000196',
  'department': 'Writing',
  'gender': 0,
  'id': 1447499,
  'job': 'Characters',
  'name': 'Bill Schwab'},
 {'credit_id': '572bd2eec3a368013d000275',
  'department': 'Directing',
  'gender': 0,
  'id': 1451279,
  'job': 'Layout',
  'name': 'Doug Walker'},
 {'credit_id': '572bce6d92514138960001e0',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1461361,
  'job': 'Visual Development',
  'name': 'Lorelay Bove'},
 {'credit_id': '572bd151c3a368012c000248',
  'department': 'Directing',
  'gender': 0,
  'id': 1461363,
  'job': 'Layout',
  'name': 'Brian Kesinger'},
 {'credit_id': '572bcbcc925141388200012d',
  'department': 'Writing',
  'gender': 0,
  'id': 1461364,
  'job': 'Characters',
  'name': 'Shiyoon Kim'},
 {'credit_id': '572bd1439251413882000243',
  'department': 'Directing',
  'gender': 0,
  'id': 1461397,
  'job': 'Layout',
  'name': 'Daniel Hu'},
 {'credit_id': '572bce8f92514138960001e3',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1461399,
  'job': 'Visual Development',
  'name': 'Lisa Keene'},
 {'credit_id': '572bc95a925141388e000121',
  'department': 'Production',
  'gender': 0,
  'id': 1464355,
  'job': 'Executive In Charge Of Post Production',
  'name': 'Bérénice Robinson'},
 {'credit_id': '572bca20925141389600012f',
  'department': 'Production',
  'gender': 0,
  'id': 1464361,
  'job': 'Production Supervisor',
  'name': 'Jennifer Christine Vera'},
 {'credit_id': '572bc8cac3a368012f00013e',
  'department': 'Lighting',
  'gender': 0,
  'id': 1470064,
  'job': 'Lighting Supervisor',
  'name': 'Josh Staub'},
 {'credit_id': '572bc5a0c3a3687ff70000b7',
  'department': 'Art',
  'gender': 2,
  'id': 1552863,
  'job': 'Art Direction',
  'name': 'David Goetz'},
 {'credit_id': '572bcf0fc3a368012f000270',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1552865,
  'job': 'Visual Development',
  'name': 'Kent Melton'},
 {'credit_id': '572bc943925141389400010e',
  'department': 'Production',
  'gender': 0,
  'id': 1554457,
  'job': 'Production Manager',
  'name': 'Doeri Welch Greiner'},
 {'credit_id': '572bd1979251413882000254',
  'department': 'Directing',
  'gender': 0,
  'id': 1578645,
  'job': 'Layout',
  'name': 'John Murrah'},
 {'credit_id': '572bc62fc3a3687ff90000e9',
  'department': 'Directing',
  'gender': 2,
  'id': 1615775,
  'job': 'Layout',
  'name': 'Scott Beattie'},
 {'credit_id': '572bc6aec3a3687ffd0000ca',
  'department': 'Crew',
  'gender': 2,
  'id': 1615776,
  'job': 'Technical Supervisor',
  'name': 'Mark Hammel'},
 {'credit_id': '572bc76b92514138850000f8',
  'department': 'Lighting',
  'gender': 2,
  'id': 1615777,
  'job': 'Lighting Supervisor',
  'name': 'Richard E. Lehmann'},
 {'credit_id': '572bc7dc92514138940000ef',
  'department': 'Lighting',
  'gender': 2,
  'id': 1615778,
  'job': 'Lighting Supervisor',
  'name': 'Robert L. Miles'},
 {'credit_id': '572bc813c3a3687ff9000136',
  'department': 'Lighting',
  'gender': 2,
  'id': 1615779,
  'job': 'Lighting Supervisor',
  'name': 'Brian Leach'},
 {'credit_id': '572bc84e925141388e00010c',
  'department': 'Lighting',
  'gender': 0,
  'id': 1615780,
  'job': 'Lighting Supervisor',
  'name': 'Alessandro Jacomini'},
 {'credit_id': '572bc88dc3a368013d0000fd',
  'department': 'Lighting',
  'gender': 2,
  'id': 1615781,
  'job': 'Lighting Supervisor',
  'name': 'Ernest J. Petti'},
 {'credit_id': '572bc8e3c3a3680140000100',
  'department': 'Lighting',
  'gender': 0,
  'id': 1615782,
  'job': 'Lighting Supervisor',
  'name': 'Chris Springfield'},
 {'credit_id': '572bcbd8c3a368013300015c',
  'department': 'Writing',
  'gender': 0,
  'id': 1615783,
  'job': 'Characters',
  'name': 'Jin Kim'},
 {'credit_id': '572bccae9251413885000196',
  'department': 'Visual Effects',
  'gender': 1,
  'id': 1615784,
  'job': 'Visual Development',
  'name': 'Lauren Airriess'},
 {'credit_id': '572bcd5cc3a368014000019e',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1615785,
  'job': 'Visual Development',
  'name': 'Justin Cram'},
 {'credit_id': '572bcdb0925141388e0001e1',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1615786,
  'job': 'Visual Development',
  'name': 'Gustaf Aspegren'},
 {'credit_id': '572bcea7c3a368013d0001e4',
  'department': 'Visual Effects',
  'gender': 1,
  'id': 1615787,
  'job': 'Visual Development',
  'name': 'Claire Keane'},
 {'credit_id': '572bcf05c3a368012c0001f6',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1615788,
  'job': 'Visual Development',
  'name': 'Craig Mullins'},
 {'credit_id': '572bcf87c3a368012c000219',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1615789,
  'job': 'Visual Development',
  'name': 'Scott Watanabe'},
 {'credit_id': '572bcf979251413894000216',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1615790,
  'job': 'Visual Development',
  'name': 'Victoria Ying'},
 {'credit_id': '572bd038925141388800021a',
  'department': 'Directing',
  'gender': 0,
  'id': 1615791,
  'job': 'Layout',
  'name': 'Cory Rocco Florimonte'},
 {'credit_id': '572bd093c3a3687ff700022f',
  'department': 'Directing',
  'gender': 2,
  'id': 1615792,
  'job': 'Layout',
  'name': 'Allen Blaisdell'},
 {'credit_id': '572bd0c9c3a368012f0002af',
  'department': 'Directing',
  'gender': 2,
  'id': 1615793,
  'job': 'Layout',
  'name': 'Rob Dressel'},
 {'credit_id': '572bd11a925141388e000264',
  'department': 'Directing',
  'gender': 0,
  'id': 1615794,
  'job': 'Layout',
  'name': 'Todd Allen Erickson'},
 {'credit_id': '572bd15d925141388800024b',
  'department': 'Directing',
  'gender': 0,
  'id': 1615795,
  'job': 'Layout',
  'name': 'Terry Moews'},
 {'credit_id': '572bd1b5c3a3687ff7000271',
  'department': 'Directing',
  'gender': 2,
  'id': 1615796,
  'job': 'Layout',
  'name': 'Christopher K. Poplin'},
 {'credit_id': '572bd2069251413888000267',
  'department': 'Directing',
  'gender': 2,
  'id': 1615797,
  'job': 'Layout',
  'name': 'Wally Schaab'},
 {'credit_id': '572bd2ccc3a368012c00026c',
  'department': 'Directing',
  'gender': 0,
  'id': 1615799,
  'job': 'Layout',
  'name': 'Richard Turner'},
 {'credit_id': '572bd309925141388800027f',
  'department': 'Directing',
  'gender': 0,
  'id': 1615800,
  'job': 'Layout',
  'name': 'David Wainstain'},
 {'credit_id': '572bd3f9925141388200029f',
  'department': 'Crew',
  'gender': 2,
  'id': 1615802,
  'job': 'Software Engineer',
  'name': 'Brent Burley'},
 {'credit_id': '572bd403c3a36801400002ac',
  'department': 'Crew',
  'gender': 2,
  'id': 1615803,
  'job': 'Software Engineer',
  'name': 'Brendan Duncan'},
 {'credit_id': '58ac80fa92514158f60148f7',
  'department': 'Crew',
  'gender': 0,
  'id': 1763017,
  'job': 'Supervising Animator',
  'name': 'Mark Mitchell'}]

In [75]:
import numpy as np

def get_director(crew):
  for crew_member in crew:
    if crew_member['job'] == 'Director':
      return crew_member['name']
  return np.nan
result_df['director']=result_df['crew'].apply(get_director)
result_df[['original_title','director']].head()

                original_title           director
1881  The Shawshank Redemption     Frank Darabont
662                 Fight Club      David Fincher
65             The Dark Knight  Christopher Nolan
3232              Pulp Fiction  Quentin Tarantino
96                   Inception  Christopher Nolan

In [76]:
result_df.loc[0].at['cast']

['Sam Worthington',
 'Zoe Saldana',
 'Sigourney Weaver',
 'Stephen Lang',
 'Michelle Rodriguez',
 'Giovanni Ribisi',
 'Joel David Moore',
 'CCH Pounder',
 'Wes Studi',
 'Laz Alonso',
 'Dileep Rao',
 'Matt Gerald',
 'Sean Anthony Moran',
 'Jason Whyte',
 'Scott Lawrence',
 'Kelly Kilgour',
 'James Patrick Pitt',
 'Sean Patrick Murphy',
 'Peter Dillon',
 'Kevin Dorman',
 'Kelson Henderson',
 'David Van Horn',
 'Jacob Tomuri',
 'Michael Blain-Rozgay',
 'Jon Curry',
 'Luke Hawker',
 'Woody Schultz',
 'Peter Mensah',
 'Sonia Yee',
 'Jahnel Curfman',
 'Ilram Choi',
 'Kyla Warren',
 'Lisa Roumain',
 'Debra Wilson',
 'Chris Mala',
 'Taylor Kibby',
 'Jodie Landau',
 'Julie Lamm',
 'Cullen B. Madden',
 'Joseph Brady Madden',
 'Frankie Torres',
 'Austin Wilson',
 'Sara Wilson',
 'Tamica Washington-Miller',
 'Lucy Briant',
 'Nathan Meister',
 'Gerry Blair',
 'Matthew Chamberlain',
 'Paul Yates',
 'Wray Wilson',
 'James Gaylyn',
 'Melvin Leno Clark III',
 'Carvon Futrell',
 'Brandon Jelkes',
 'Micah Moch',
 'Hanniyah Muhammad',
 'Christopher Nolen',
 'Christa Oliver',
 'April Marie Thomas',
 'Bravita A. Threatt',
 'Colin Bleasdale',
 'Mike Bodnar',
 'Matt Clayton',
 'Nicole Dionne',
 'Jamie Harrison',
 'Allan Henry',
 'Anthony Ingruber',
 'Ashley Jeffery',
 'Dean Knowsley',
 'Joseph Mika-Hunt',
 'Terry Notary',
 'Kai Pantano',
 'Logan Pithyou',
 'Stuart Pollock',
 'Raja',
 'Gareth Ruck',
 'Rhian Sheehan',
 'T. J. Storm',
 'Jodie Taylor',
 'Alicia Vela-Bailey',
 'Richard Whiteside',
 'Nikie Zambo',
 'Julene Renee']

In [77]:
result_df.loc[0].at['keywords']

[{'id': 1463, 'name': 'culture clash'},
 {'id': 2964, 'name': 'future'},
 {'id': 3386, 'name': 'space war'},
 {'id': 3388, 'name': 'space colony'},
 {'id': 3679, 'name': 'society'},
 {'id': 3801, 'name': 'space travel'},
 {'id': 9685, 'name': 'futuristic'},
 {'id': 9840, 'name': 'romance'},
 {'id': 9882, 'name': 'space'},
 {'id': 9951, 'name': 'alien'},
 {'id': 10148, 'name': 'tribe'},
 {'id': 10158, 'name': 'alien planet'},
 {'id': 10987, 'name': 'cgi'},
 {'id': 11399, 'name': 'marine'},
 {'id': 13065, 'name': 'soldier'},
 {'id': 14643, 'name': 'battle'},
 {'id': 14720, 'name': 'love affair'},
 {'id': 165431, 'name': 'anti war'},
 {'id': 193554, 'name': 'power relations'},
 {'id': 206690, 'name': 'mind and soul'},
 {'id': 209714, 'name': '3d'}]

In [78]:
result_df.loc[0].at['genres']

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [ ]:
def get_name_list(column_value):
  names_list=[]
  if isinstance(column_value,list):
    for element in column_value:
      names_list.append(element['name'])
  return names_list
features=['cast','keywords','genres','director']
for feature in features:

  result_df[feature]=result_df[feature].apply(get_name_list)
  result_df[['cast','keywords','genres','director']].head(3)